import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const PRODUCTS = [
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Kit Balões Metálicos Dourado e Roxo - 50 unidades',
    slug: 'kit-baloes-metalicos-dourado-roxo-50un',
    description:
      'Kit premium com 50 balões metálicos nas cores dourado e roxo. Ideais para decoração de festas de aniversário, casamentos e eventos corporativos. Feitos em látex de alta qualidade com acabamento metalizado.',
    shortDescription: 'Kit com 50 balões metálicos dourado e roxo para festas.',
    price: 49.9,
    originalPrice: 69.9,
    currency: 'BRL',
    category: 'baloes',
    subcategory: 'metalicos',
    images: ['https://picsum.photos/seed/baloes1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/baloes1/300/300',
    badges: ['mais-vendido', 'promocao'],
    specifications: {
      Material: 'Látex metalizado',
      Quantidade: '50 unidades',
      Tamanho: '12 polegadas',
      Cores: 'Dourado e Roxo',
    },
    stock: 150,
    sku: 'BAL-MET-DR-50',
    weight: 0.3,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 16.63,
  },
  {
    id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Conjunto Pratos e Copos Descartáveis Premium - 100 peças',
    slug: 'conjunto-pratos-copos-descartaveis-premium-100pc',
    description:
      'Conjunto completo com 50 pratos e 50 copos descartáveis premium. Material resistente e elegante, perfeito para festas e eventos. Disponível na cor branca com borda dourada.',
    shortDescription: '100 peças de pratos e copos descartáveis premium.',
    price: 89.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'descartaveis',
    subcategory: 'conjuntos',
    images: ['https://picsum.photos/seed/desc1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/desc1/300/300',
    badges: ['novo'],
    specifications: {
      Material: 'Plástico rígido PP',
      Quantidade: '50 pratos + 50 copos',
      'Capacidade copo': '300ml',
      'Tamanho prato': '23cm',
    },
    stock: 80,
    sku: 'DESC-PC-PREM-100',
    weight: 1.2,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 29.97,
  },
  {
    id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'Cortina de Franja Metalizada Rosa Gold',
    slug: 'cortina-franja-metalizada-rosa-gold',
    description:
      'Cortina decorativa de franja metalizada na cor rosa gold. Dimensões 1m x 2m. Perfeita para fundo de mesa de bolo, photobooth e decoração de ambientes.',
    shortDescription: 'Cortina metalizada rosa gold 1m x 2m.',
    price: 24.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'decoracao',
    subcategory: 'cortinas',
    images: ['https://picsum.photos/seed/cortina1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/cortina1/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'PET metalizado',
      Dimensões: '1m x 2m',
      Cor: 'Rosa Gold',
      Fixação: 'Fita adesiva inclusa',
    },
    stock: 200,
    sku: 'DEC-CORT-RG-1X2',
    weight: 0.15,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: 'd4e5f6a7-b8c9-0123-def0-234567890123',
    name: 'Kit Festa Completo Tema Unicórnio - 16 Convidados',
    slug: 'kit-festa-completo-unicornio-16-convidados',
    description:
      'Kit festa completo tema unicórnio para 16 convidados. Inclui pratos, copos, guardanapos, toalha de mesa, convites, forminhas para doce e chapéus. Tudo coordenado no tema.',
    shortDescription: 'Kit festa unicórnio completo para 16 convidados.',
    price: 129.9,
    originalPrice: 159.9,
    currency: 'BRL',
    category: 'kits',
    subcategory: 'tematicos',
    images: ['https://picsum.photos/seed/kit1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/kit1/300/300',
    badges: ['promocao', 'mais-vendido'],
    specifications: {
      Convidados: '16 pessoas',
      'Itens inclusos': '7 tipos de itens',
      Tema: 'Unicórnio',
      'Total peças': '112 peças',
    },
    stock: 45,
    sku: 'KIT-UNI-16',
    weight: 1.8,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 21.65,
  },
  {
    id: 'e5f6a7b8-c9d0-1234-ef01-345678901234',
    name: 'Forminha para Doces Luxo Dourada - 100 unidades',
    slug: 'forminha-doces-luxo-dourada-100un',
    description:
      'Forminhas para doces finos em papel laminado dourado. Modelo luxo com recorte em pétala. Ideais para brigadeiros, bem-casados e docinhos finos.',
    shortDescription: 'Forminhas douradas luxo para docinhos - 100 un.',
    price: 34.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'doces',
    subcategory: 'forminhas',
    images: ['https://picsum.photos/seed/forminha1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/forminha1/300/300',
    badges: ['exclusivo'],
    specifications: {
      Material: 'Papel laminado',
      Quantidade: '100 unidades',
      Modelo: 'Pétala luxo',
      'Diâmetro base': '3.5cm',
    },
    stock: 300,
    sku: 'DOC-FORM-LUXO-100',
    weight: 0.1,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: 'f6a7b8c9-d0e1-2345-f012-456789012345',
    name: 'Vela Número Gigante Glitter - Todas as Idades',
    slug: 'vela-numero-gigante-glitter',
    description:
      'Vela decorativa em formato de número com acabamento glitter. Altura de 12cm. Disponível em todos os números de 0 a 9. Longa duração de queima.',
    shortDescription: 'Vela número gigante com glitter, 12cm.',
    price: 18.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'velas',
    subcategory: null,
    images: ['https://picsum.photos/seed/vela1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/vela1/300/300',
    badges: ['novo'],
    specifications: {
      Altura: '12cm',
      Material: 'Parafina com glitter',
      'Tempo queima': '~15 minutos',
      'Números disponíveis': '0 a 9',
    },
    stock: 500,
    sku: 'VEL-NUM-GLIT',
    weight: 0.05,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: 'a7b8c9d0-e1f2-3456-0123-567890123456',
    name: 'Convites Personalizados Festa Tropical - 20 unidades',
    slug: 'convites-personalizados-festa-tropical-20un',
    description:
      'Kit com 20 convites impressos em papel couchê 300g no tema festa tropical. Inclui envelopes kraft. Personalização de nome e data da festa inclusa.',
    shortDescription: 'Convites festa tropical com envelopes - 20 un.',
    price: 42.0,
    originalPrice: null,
    currency: 'BRL',
    category: 'convites',
    subcategory: 'impressos',
    images: ['https://picsum.photos/seed/convite1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/convite1/300/300',
    badges: [],
    specifications: {
      Papel: 'Couchê 300g',
      Quantidade: '20 convites + 20 envelopes',
      Tamanho: '10cm x 15cm',
      Personalização: 'Nome e data',
    },
    stock: 60,
    sku: 'CONV-TROP-20',
    weight: 0.25,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 21.0,
  },
  {
    id: 'b8c9d0e1-f2a3-4567-1234-678901234567',
    name: 'Fantasia Infantil Princesa com Tiara e Varinha',
    slug: 'fantasia-infantil-princesa-tiara-varinha',
    description:
      'Fantasia infantil de princesa com vestido em tule, tiara com pedras brilhantes e varinha mágica. Disponível nos tamanhos P (2-4 anos), M (5-7 anos) e G (8-10 anos).',
    shortDescription: 'Fantasia princesa com tiara e varinha para crianças.',
    price: 79.9,
    originalPrice: 99.9,
    currency: 'BRL',
    category: 'fantasias',
    subcategory: 'infantil',
    images: ['https://picsum.photos/seed/fantasia1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/fantasia1/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'Poliéster e tule',
      'Tamanhos disponíveis': 'P, M, G',
      'Faixa etária': '2 a 10 anos',
      'Itens inclusos': 'Vestido, tiara, varinha',
    },
    stock: 35,
    sku: 'FANT-PRINC-KIT',
    weight: 0.4,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 26.63,
  },
  {
    id: 'c9d0e1f2-a3b4-5678-2345-789012345678',
    name: 'Óculos Festa Neon LED - Kit 10 Unidades Cores Sortidas',
    slug: 'oculos-festa-neon-led-kit-10un',
    description:
      'Kit com 10 óculos de festa com LED neon em cores sortidas (rosa, verde, azul, amarelo, vermelho). 3 modos de luz: fixo, pisca lento e pisca rápido. Bateria inclusa.',
    shortDescription: 'Kit 10 óculos neon LED cores sortidas para festa.',
    price: 59.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'acessorios',
    subcategory: 'luminosos',
    images: ['https://picsum.photos/seed/oculos1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/oculos1/300/300',
    badges: ['mais-vendido', 'novo'],
    specifications: {
      Quantidade: '10 unidades',
      Cores: '5 cores sortidas',
      'Modos de luz': '3 modos',
      Bateria: 'CR2032 inclusa',
    },
    stock: 120,
    sku: 'ACESS-OCULOS-LED-10',
    weight: 0.5,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 19.97,
  },
  {
    id: 'd0e1f2a3-b4c5-6789-3456-890123456789',
    name: 'Faixa de Aniversário Personalizada com Nome - Banner TNT',
    slug: 'faixa-aniversario-personalizada-banner-tnt',
    description:
      'Faixa de aniversário em TNT com impressão personalizada. Inclui nome do aniversariante e idade. Dimensões 1.5m x 0.7m. Acompanha fita para fixação.',
    shortDescription: 'Faixa aniversário personalizada em TNT 1.5m x 0.7m.',
    price: 55.0,
    originalPrice: null,
    currency: 'BRL',
    category: 'personalizados',
    subcategory: 'faixas',
    images: ['https://picsum.photos/seed/faixa1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/faixa1/300/300',
    badges: ['exclusivo'],
    specifications: {
      Material: 'TNT laminado',
      Dimensões: '1.5m x 0.7m',
      Personalização: 'Nome e idade',
      Fixação: 'Fita inclusa',
    },
    stock: 25,
    sku: 'PERS-FAIXA-TNT',
    weight: 0.2,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 27.5,
  },

  // ── BALOES (4 new) ──────────────────────────────────────────────────
  {
    id: '10000001-0001-4000-a001-000000000001',
    name: 'Balões Perolados Pastel - 25 unidades',
    slug: 'baloes-perolados-pastel-25un',
    description:
      'Kit com 25 balões perolados em tons pastel (rosa, azul, lilás, verde e amarelo). Feitos em látex natural premium com acabamento perolado suave, ideais para chás de bebê, batizados e aniversários infantis.',
    shortDescription: '25 balões perolados em tons pastel sortidos.',
    price: 29.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'baloes',
    subcategory: 'perolados',
    images: ['https://picsum.photos/seed/baloes2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/baloes2/300/300',
    badges: ['novo'],
    specifications: {
      Material: 'Látex natural perolado',
      Quantidade: '25 unidades',
      Tamanho: '11 polegadas',
      Cores: '5 tons pastel sortidos',
    },
    stock: 220,
    sku: 'BAL-PERL-PAST-25',
    weight: 0.15,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 14.95,
  },
  {
    id: '10000001-0001-4000-a001-000000000002',
    name: 'Balão Gigante Transparente com Confetes Dourados',
    slug: 'balao-gigante-transparente-confetes-dourados',
    description:
      'Balão gigante de 36 polegadas em látex transparente cristal, acompanhado de 15g de confetes metalizados dourados. Perfeito para decoração de entradas, mesas principais e ensaios fotográficos.',
    shortDescription: 'Balão gigante 36" transparente com confetes dourados.',
    price: 22.9,
    originalPrice: 29.9,
    currency: 'BRL',
    category: 'baloes',
    subcategory: 'gigantes',
    images: ['https://picsum.photos/seed/baloes3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/baloes3/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'Látex cristal',
      Quantidade: '1 balão + 15g confetes',
      Tamanho: '36 polegadas',
      Confete: 'Papel metalizado dourado',
    },
    stock: 180,
    sku: 'BAL-GIG-CONF-DOU',
    weight: 0.08,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000001-0001-4000-a001-000000000003',
    name: 'Arco Desconstruído de Balões Safari - 120 peças',
    slug: 'arco-desconstruido-baloes-safari-120pc',
    description:
      'Kit completo para montar arco desconstruído no tema safari. Inclui 120 balões em verde musgo, nude, marrom e branco, além de folhas artificiais e fita para montagem. Resultado profissional sem precisar de curso.',
    shortDescription: 'Kit arco desconstruído safari com 120 balões e acessórios.',
    price: 89.9,
    originalPrice: 119.9,
    currency: 'BRL',
    category: 'baloes',
    subcategory: 'arcos',
    images: ['https://picsum.photos/seed/baloes4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/baloes4/300/300',
    badges: ['mais-vendido', 'promocao'],
    specifications: {
      Material: 'Látex premium',
      Quantidade: '120 balões + acessórios',
      Tamanho: '5", 10" e 18"',
      'Itens extras': 'Folhas + fita + cola ponto',
    },
    stock: 65,
    sku: 'BAL-ARCO-SAF-120',
    weight: 0.6,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 29.97,
  },
  {
    id: '10000001-0001-4000-a001-000000000004',
    name: 'Balões de Número Metalizado Prata - 70cm',
    slug: 'baloes-numero-metalizado-prata-70cm',
    description:
      'Balão metalizado em formato de número na cor prata. Altura de 70cm. Pode ser inflado com hélio ou ar. Disponível nos números 0 a 9. Ideal para marcar a idade em festas de aniversário.',
    shortDescription: 'Balão número metalizado prata 70cm, números 0-9.',
    price: 15.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'baloes',
    subcategory: 'metalicos',
    images: ['https://picsum.photos/seed/baloes5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/baloes5/300/300',
    badges: [],
    specifications: {
      Material: 'Filme metalizado (mylar)',
      Quantidade: '1 unidade',
      Altura: '70cm',
      Inflável: 'Hélio ou ar',
    },
    stock: 350,
    sku: 'BAL-NUM-MET-PRT-70',
    weight: 0.04,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },

  // ── DESCARTAVEIS (4 new) ────────────────────────────────────────────
  {
    id: '10000002-0001-4000-a002-000000000001',
    name: 'Guardanapos Decorados Folha de Ouro - 40 unidades',
    slug: 'guardanapos-decorados-folha-ouro-40un',
    description:
      'Guardanapos de papel tripla camada com estampa de folha de ouro. Tamanho 33x33cm aberto. Material macio e absorvente, ideal para festas sofisticadas e jantares especiais.',
    shortDescription: 'Guardanapos tripla camada com folha de ouro - 40 un.',
    price: 19.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'descartaveis',
    subcategory: 'guardanapos',
    images: ['https://picsum.photos/seed/desc2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/desc2/300/300',
    badges: ['novo'],
    specifications: {
      Material: 'Papel tripla camada',
      Quantidade: '40 unidades',
      Tamanho: '33cm x 33cm (aberto)',
      Estampa: 'Folha de ouro',
    },
    stock: 160,
    sku: 'DESC-GUARD-OURO-40',
    weight: 0.25,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000002-0001-4000-a002-000000000002',
    name: 'Talheres Descartáveis Rose Gold Premium - 60 peças',
    slug: 'talheres-descartaveis-rose-gold-premium-60pc',
    description:
      'Kit com 20 garfos, 20 facas e 20 colheres descartáveis na cor rose gold. Plástico rígido reforçado com acabamento metalizado premium. Elegante e resistente para qualquer celebração.',
    shortDescription: 'Talheres descartáveis rose gold - 60 peças (garfo, faca, colher).',
    price: 39.9,
    originalPrice: 49.9,
    currency: 'BRL',
    category: 'descartaveis',
    subcategory: 'talheres',
    images: ['https://picsum.photos/seed/desc3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/desc3/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'PS rígido metalizado',
      Quantidade: '20 garfos + 20 facas + 20 colheres',
      Cor: 'Rose Gold',
      Resistência: 'Reforçado',
    },
    stock: 95,
    sku: 'DESC-TALH-RG-60',
    weight: 0.45,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 19.95,
  },
  {
    id: '10000002-0001-4000-a002-000000000003',
    name: 'Canudos de Papel Biodegradáveis Coloridos - 100 unidades',
    slug: 'canudos-papel-biodegradaveis-coloridos-100un',
    description:
      'Kit com 100 canudos de papel biodegradável em 5 cores vibrantes (vermelho, azul, verde, amarelo e rosa). Resistentes a líquidos por até 3 horas. Ecológicos e livres de plástico.',
    shortDescription: 'Canudos de papel coloridos biodegradáveis - 100 un.',
    price: 14.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'descartaveis',
    subcategory: 'canudos',
    images: ['https://picsum.photos/seed/desc4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/desc4/300/300',
    badges: ['exclusivo'],
    specifications: {
      Material: 'Papel kraft biodegradável',
      Quantidade: '100 unidades',
      Cores: '5 cores sortidas',
      Durabilidade: 'Até 3 horas em líquidos',
    },
    stock: 250,
    sku: 'DESC-CANU-BIO-100',
    weight: 0.2,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000002-0001-4000-a002-000000000004',
    name: 'Toalha de Mesa Descartável Branca com Borda Dourada',
    slug: 'toalha-mesa-descartavel-branca-borda-dourada',
    description:
      'Toalha de mesa descartável em TNT branco com borda estampada em dourado. Tamanho 1.40m x 2.20m. Perfeita para mesas retangulares de 6 a 8 lugares.',
    shortDescription: 'Toalha de mesa TNT branca com borda dourada 1.40x2.20m.',
    price: 24.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'descartaveis',
    subcategory: 'toalhas',
    images: ['https://picsum.photos/seed/desc5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/desc5/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'TNT laminado',
      Dimensões: '1.40m x 2.20m',
      Cor: 'Branco com borda dourada',
      'Indicado para': 'Mesas de 6 a 8 lugares',
    },
    stock: 130,
    sku: 'DESC-TOALH-BD-140',
    weight: 0.35,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },

  // ── DECORACAO (4 new) ───────────────────────────────────────────────
  {
    id: '10000003-0001-4000-a003-000000000001',
    name: 'Pompom de Papel de Seda - Kit 8 unidades Cores Sortidas',
    slug: 'pompom-papel-seda-kit-8un-cores-sortidas',
    description:
      'Kit com 8 pompons de papel de seda em tamanhos variados (15cm, 20cm e 25cm). Cores sortidas: rosa, branco, dourado e lilás. Acompanha fio de nylon para pendurar. Decoração elegante para festas.',
    shortDescription: 'Kit 8 pompons de papel de seda cores sortidas.',
    price: 32.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'decoracao',
    subcategory: 'papel',
    images: ['https://picsum.photos/seed/deco2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/deco2/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'Papel de seda',
      Quantidade: '8 pompons',
      Tamanhos: '15cm, 20cm e 25cm',
      Fixação: 'Fio de nylon incluso',
    },
    stock: 170,
    sku: 'DEC-POMP-SEDA-8',
    weight: 0.12,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 16.45,
  },
  {
    id: '10000003-0001-4000-a003-000000000002',
    name: 'Painel Redondo para Festa - Estrutura + Tecido Sublimado',
    slug: 'painel-redondo-festa-estrutura-tecido-sublimado',
    description:
      'Painel redondo para fundo de mesa com estrutura metálica desmontável e capa de tecido sublimado. Diâmetro 1.50m. Perfeito para mesa de bolo. Diversos temas disponíveis.',
    shortDescription: 'Painel redondo 1.50m com estrutura + tecido sublimado.',
    price: 149.9,
    originalPrice: 189.9,
    currency: 'BRL',
    category: 'decoracao',
    subcategory: 'paineis',
    images: ['https://picsum.photos/seed/deco3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/deco3/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'Metal + tecido sublimado',
      Diâmetro: '1.50m',
      Montagem: 'Encaixe sem ferramentas',
      Reutilizável: 'Sim (troca de capa)',
    },
    stock: 30,
    sku: 'DEC-PAIN-RED-150',
    weight: 3.5,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 24.98,
  },
  {
    id: '10000003-0001-4000-a003-000000000003',
    name: 'Letras Luminosas LED "LOVE" - 22cm',
    slug: 'letras-luminosas-led-love-22cm',
    description:
      'Letras decorativas em LED formando a palavra LOVE. Cada letra tem 22cm de altura. Alimentação por 2 pilhas AA (não inclusas). Luz branca quente. Ideal para casamentos, noivados e datas românticas.',
    shortDescription: 'Letras luminosas LED "LOVE" 22cm, branco quente.',
    price: 64.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'decoracao',
    subcategory: 'luminosos',
    images: ['https://picsum.photos/seed/deco4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/deco4/300/300',
    badges: ['exclusivo'],
    specifications: {
      Material: 'Plástico ABS',
      Altura: '22cm por letra',
      'Tipo luz': 'LED branco quente',
      Alimentação: '2x AA (não inclusas)',
    },
    stock: 55,
    sku: 'DEC-LED-LOVE-22',
    weight: 0.6,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 21.63,
  },
  {
    id: '10000003-0001-4000-a003-000000000004',
    name: 'Bandeirinha de Juta "Feliz Aniversário" - 2.5m',
    slug: 'bandeirinha-juta-feliz-aniversario-2-5m',
    description:
      'Bandeirinha rústica em juta natural com letras "FELIZ ANIVERSÁRIO" impressas em dourado. Comprimento total 2.5m com 18 bandeirolas. Ideal para festas com tema rústico, fazendinha ou garden party.',
    shortDescription: 'Bandeirinha de juta "FELIZ ANIVERSÁRIO" 2.5m, letras douradas.',
    price: 27.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'decoracao',
    subcategory: 'bandeirinhas',
    images: ['https://picsum.photos/seed/deco5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/deco5/300/300',
    badges: ['novo'],
    specifications: {
      Material: 'Juta natural',
      Comprimento: '2.5m',
      Bandeirolas: '18 unidades',
      Estilo: 'Rústico dourado',
    },
    stock: 90,
    sku: 'DEC-BAND-JUTA-FA',
    weight: 0.18,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },

  // ── KITS (4 new) ───────────────────────────────────────────────────
  {
    id: '10000004-0001-4000-a004-000000000001',
    name: 'Kit Festa Completo Tema Safari - 24 Convidados',
    slug: 'kit-festa-completo-safari-24-convidados',
    description:
      'Kit festa completo no tema safari para 24 convidados. Inclui pratos, copos, guardanapos, toalha de mesa, chapéus, forminhas para doce, convites e sacolinhas surpresa. Estampa coordenada com animais da selva.',
    shortDescription: 'Kit festa safari completo para 24 convidados.',
    price: 179.9,
    originalPrice: 219.9,
    currency: 'BRL',
    category: 'kits',
    subcategory: 'tematicos',
    images: ['https://picsum.photos/seed/kit2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/kit2/300/300',
    badges: ['promocao'],
    specifications: {
      Convidados: '24 pessoas',
      'Itens inclusos': '8 tipos de itens',
      Tema: 'Safari / Animais da Selva',
      'Total peças': '192 peças',
    },
    stock: 30,
    sku: 'KIT-SAF-24',
    weight: 2.5,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 29.98,
  },
  {
    id: '10000004-0001-4000-a004-000000000002',
    name: 'Kit Chá de Bebê Menino - Azul e Branco 20 Convidados',
    slug: 'kit-cha-bebe-menino-azul-branco-20-convidados',
    description:
      'Kit completo para chá de bebê de menino nas cores azul e branco. Para 20 convidados. Inclui pratos, copos, guardanapos, toalha, banner decorativo, toppers de mesa e lembrancinhas em caixa.',
    shortDescription: 'Kit chá de bebê azul e branco para 20 convidados.',
    price: 159.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'kits',
    subcategory: 'cha-bebe',
    images: ['https://picsum.photos/seed/kit3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/kit3/300/300',
    badges: ['novo'],
    specifications: {
      Convidados: '20 pessoas',
      'Itens inclusos': '9 tipos de itens',
      Tema: 'Chá de bebê menino',
      Cores: 'Azul e branco',
    },
    stock: 25,
    sku: 'KIT-CHA-MEN-20',
    weight: 2.2,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 26.65,
  },
  {
    id: '10000004-0001-4000-a004-000000000003',
    name: 'Kit Festa Neon Glow Party - 30 Convidados',
    slug: 'kit-festa-neon-glow-party-30-convidados',
    description:
      'Kit festa neon para 30 convidados com itens fluorescentes. Inclui copos, pratos e guardanapos neon, pulseiras luminosas, tintas UV faciais, toppers e banner "GLOW PARTY". Perfeito para festas noturnas.',
    shortDescription: 'Kit festa neon/glow para 30 convidados com itens fluorescentes.',
    price: 249.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'kits',
    subcategory: 'tematicos',
    images: ['https://picsum.photos/seed/kit4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/kit4/300/300',
    badges: ['exclusivo', 'mais-vendido'],
    specifications: {
      Convidados: '30 pessoas',
      'Itens inclusos': '10 tipos de itens',
      Tema: 'Neon / Glow Party',
      Destaque: 'Pulseiras luminosas + tintas UV',
    },
    stock: 20,
    sku: 'KIT-NEON-30',
    weight: 3.0,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 41.65,
  },
  {
    id: '10000004-0001-4000-a004-000000000004',
    name: 'Kit Festa Adulto Churrasco & Boteco - 20 Convidados',
    slug: 'kit-festa-adulto-churrasco-boteco-20-convidados',
    description:
      'Kit temático para festa de adulto estilo churrasco/boteco. Para 20 convidados. Inclui pratos, copos, guardanapos estampados, toalha xadrez, bandeirolas, plaquinhas divertidas para fotos e porta-copos.',
    shortDescription: 'Kit festa adulto churrasco/boteco para 20 convidados.',
    price: 139.9,
    originalPrice: 169.9,
    currency: 'BRL',
    category: 'kits',
    subcategory: 'adulto',
    images: ['https://picsum.photos/seed/kit5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/kit5/300/300',
    badges: ['promocao'],
    specifications: {
      Convidados: '20 pessoas',
      'Itens inclusos': '8 tipos de itens',
      Tema: 'Churrasco / Boteco',
      Destaque: 'Plaquinhas divertidas para fotos',
    },
    stock: 40,
    sku: 'KIT-CHURR-BOT-20',
    weight: 2.0,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 23.32,
  },

  // ── DOCES (4 new) ──────────────────────────────────────────────────
  {
    id: '10000005-0001-4000-a005-000000000001',
    name: 'Cachepot para Doces Listrado Azul e Branco - 10 unidades',
    slug: 'cachepot-doces-listrado-azul-branco-10un',
    description:
      'Cachepots em papel cartão listrado azul e branco para mesa de doces. Tamanho ideal para brigadeiros, bombons e docinhos finos. Montagem fácil sem cola.',
    shortDescription: 'Cachepot listrado azul/branco para doces - 10 un.',
    price: 18.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'doces',
    subcategory: 'cachepots',
    images: ['https://picsum.photos/seed/doce2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/doce2/300/300',
    badges: [],
    specifications: {
      Material: 'Papel cartão 300g',
      Quantidade: '10 unidades',
      'Dimensão base': '6cm x 6cm',
      Altura: '6cm',
    },
    stock: 200,
    sku: 'DOC-CACHE-AB-10',
    weight: 0.12,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000005-0001-4000-a005-000000000002',
    name: 'Caixa para Cupcake Individual com Visor - 12 unidades',
    slug: 'caixa-cupcake-individual-visor-12un',
    description:
      'Caixas individuais para cupcake em papel kraft com visor transparente. Perfeitas para presentear, vender ou transportar cupcakes decorados com segurança.',
    shortDescription: 'Caixa individual kraft para cupcake com visor - 12 un.',
    price: 24.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'doces',
    subcategory: 'embalagens',
    images: ['https://picsum.photos/seed/doce3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/doce3/300/300',
    badges: ['novo'],
    specifications: {
      Material: 'Papel kraft + PVC transparente',
      Quantidade: '12 caixas',
      Dimensões: '9cm x 9cm x 10cm',
      Montagem: 'Encaixe sem cola',
    },
    stock: 150,
    sku: 'DOC-CX-CUP-12',
    weight: 0.18,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000005-0001-4000-a005-000000000003',
    name: 'Palito Decorativo para Doces Estrelas Glitter - 20 unidades',
    slug: 'palito-decorativo-doces-estrelas-glitter-20un',
    description:
      'Palitos decorativos com topo em formato de estrela com acabamento glitter dourado. Ideais para brigadeiros gourmet, cupcakes e docinhos finos em festas elegantes.',
    shortDescription: 'Palitos decorativos estrela glitter dourado - 20 un.',
    price: 12.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'doces',
    subcategory: 'toppers',
    images: ['https://picsum.photos/seed/doce4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/doce4/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'Madeira + papel glitter',
      Quantidade: '20 palitos',
      'Altura total': '10cm',
      'Topo estrela': '3cm',
    },
    stock: 280,
    sku: 'DOC-PAL-EST-GLIT-20',
    weight: 0.06,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000005-0001-4000-a005-000000000004',
    name: 'Wrapper para Cupcake Rendado Rosa - 24 unidades',
    slug: 'wrapper-cupcake-rendado-rosa-24un',
    description:
      'Wrappers (saias) para cupcake em papel rendado na cor rosa. Criam um acabamento elegante e sofisticado. Fácil aplicação: basta envolver o cupcake já assado.',
    shortDescription: 'Wrapper rendado rosa para cupcake - 24 un.',
    price: 16.9,
    originalPrice: 22.9,
    currency: 'BRL',
    category: 'doces',
    subcategory: 'wrappers',
    images: ['https://picsum.photos/seed/doce5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/doce5/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'Papel couchê vazado',
      Quantidade: '24 unidades',
      'Diâmetro base': '5cm',
      Cor: 'Rosa',
    },
    stock: 190,
    sku: 'DOC-WRAP-REND-RS-24',
    weight: 0.05,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },

  // ── VELAS (4 new) ──────────────────────────────────────────────────
  {
    id: '10000006-0001-4000-a006-000000000001',
    name: 'Velas Palito Espiral Colorida - Kit 12 unidades',
    slug: 'velas-palito-espiral-colorida-kit-12un',
    description:
      'Kit com 12 velas palito em formato espiral com cores vibrantes sortidas. Altura 8cm. Queima longa e uniforme. Acompanham suportes individuais para bolo.',
    shortDescription: 'Velas palito espiral coloridas com suporte - 12 un.',
    price: 9.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'velas',
    subcategory: 'palito',
    images: ['https://picsum.photos/seed/vela2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/vela2/300/300',
    badges: [],
    specifications: {
      Material: 'Parafina colorida',
      Quantidade: '12 velas + 12 suportes',
      Altura: '8cm',
      Formato: 'Espiral',
    },
    stock: 400,
    sku: 'VEL-ESPIR-COLOR-12',
    weight: 0.04,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000006-0001-4000-a006-000000000002',
    name: 'Vela Fonte Faísca Dourada para Bolo - 6 unidades',
    slug: 'vela-fonte-faisca-dourada-bolo-6un',
    description:
      'Velas tipo fonte (sparkler) com faíscas douradas. Efeito espetacular para chegada do bolo. Queima por aproximadamente 45 segundos. Kit com 6 unidades.',
    shortDescription: 'Velas fonte faísca dourada para bolo - 6 un.',
    price: 22.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'velas',
    subcategory: 'sparkler',
    images: ['https://picsum.photos/seed/vela3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/vela3/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'Composição pirotécnica (NR)',
      Quantidade: '6 unidades',
      'Tempo queima': '~45 segundos',
      Efeito: 'Faísca dourada',
    },
    stock: 320,
    sku: 'VEL-FONT-DOU-6',
    weight: 0.06,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000006-0001-4000-a006-000000000003',
    name: 'Vela Musical Giratória Flor de Lótus',
    slug: 'vela-musical-giratoria-flor-lotus',
    description:
      'Vela em formato de flor de lótus que se abre girando ao ser acesa, tocando a melodia "Parabéns pra Você". Efeito surpresa encantador. Pétalas coloridas com pavio individual.',
    shortDescription: 'Vela musical giratória flor de lótus com melodia.',
    price: 19.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'velas',
    subcategory: null,
    images: ['https://picsum.photos/seed/vela4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/vela4/300/300',
    badges: ['novo', 'exclusivo'],
    specifications: {
      Material: 'Parafina + mecanismo musical',
      Quantidade: '1 unidade',
      Melodia: 'Parabéns pra Você',
      Efeito: 'Abre e gira ao acender',
    },
    stock: 180,
    sku: 'VEL-MUSIC-LOTUS',
    weight: 0.08,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000006-0001-4000-a006-000000000004',
    name: 'Vela Temática Dinossauros - Kit 5 unidades',
    slug: 'vela-tematica-dinossauros-kit-5un',
    description:
      'Kit com 5 velas em formato de dinossauros para festa infantil. Modelos: T-Rex, Triceratops, Braquiossauro, Estegossauro e Pterodáctilo. Cores vibrantes, base estável.',
    shortDescription: 'Velas em formato de dinossauros - kit 5 un.',
    price: 24.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'velas',
    subcategory: 'tematicas',
    images: ['https://picsum.photos/seed/vela5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/vela5/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'Parafina moldada',
      Quantidade: '5 unidades',
      Modelos: '5 dinossauros diferentes',
      Altura: '~5cm cada',
    },
    stock: 110,
    sku: 'VEL-DINO-KIT-5',
    weight: 0.1,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },

  // ── CONVITES (4 new) ───────────────────────────────────────────────
  {
    id: '10000007-0001-4000-a007-000000000001',
    name: 'Convites Infantil Tema Fundo do Mar - 15 unidades',
    slug: 'convites-infantil-fundo-mar-15un',
    description:
      'Kit com 15 convites infantis no tema fundo do mar. Estampa com peixinhos, conchas e estrelas-do-mar em aquarela. Papel couchê 250g com acabamento brilhante. Inclui envelopes azuis.',
    shortDescription: 'Convites tema fundo do mar com envelopes - 15 un.',
    price: 34.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'convites',
    subcategory: 'infantil',
    images: ['https://picsum.photos/seed/conv2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/conv2/300/300',
    badges: [],
    specifications: {
      Papel: 'Couchê 250g brilhante',
      Quantidade: '15 convites + 15 envelopes',
      Tamanho: '10cm x 15cm',
      Tema: 'Fundo do Mar',
    },
    stock: 75,
    sku: 'CONV-MAR-15',
    weight: 0.2,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 17.45,
  },
  {
    id: '10000007-0001-4000-a007-000000000002',
    name: 'Convite Digital Animado Aniversário - Pacote Personalização',
    slug: 'convite-digital-animado-aniversario-personalizacao',
    description:
      'Convite digital animado em formato MP4 para WhatsApp e redes sociais. Personalização completa: nome, idade, data, horário e local. Entrega em até 48h após aprovação do layout. Vários temas disponíveis.',
    shortDescription: 'Convite digital animado personalizado para WhatsApp.',
    price: 49.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'convites',
    subcategory: 'digitais',
    images: ['https://picsum.photos/seed/conv3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/conv3/300/300',
    badges: ['mais-vendido', 'exclusivo'],
    specifications: {
      Formato: 'MP4 animado',
      Duração: '15 segundos',
      Entrega: 'Digital em até 48h',
      Personalização: 'Nome, idade, data, local',
    },
    stock: 999,
    sku: 'CONV-DIGIT-ANIM',
    weight: 0.0,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 24.95,
  },
  {
    id: '10000007-0001-4000-a007-000000000003',
    name: 'Convites Casamento Rústico Kraft - 30 unidades',
    slug: 'convites-casamento-rustico-kraft-30un',
    description:
      'Kit com 30 convites de casamento em papel kraft 350g com detalhes em renda branca e laço de sisal. Texto interno personalizável. Acompanham envelopes kraft e adesivos de fechamento.',
    shortDescription: 'Convites casamento rústico kraft com renda - 30 un.',
    price: 89.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'convites',
    subcategory: 'casamento',
    images: ['https://picsum.photos/seed/conv4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/conv4/300/300',
    badges: ['novo'],
    specifications: {
      Papel: 'Kraft 350g',
      Quantidade: '30 convites + envelopes + adesivos',
      Tamanho: '15cm x 21cm',
      Detalhes: 'Renda branca + laço de sisal',
    },
    stock: 35,
    sku: 'CONV-CAS-KRAFT-30',
    weight: 0.6,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 29.97,
  },
  {
    id: '10000007-0001-4000-a007-000000000004',
    name: 'Convites Pop-Up 3D Festa Junina - 10 unidades',
    slug: 'convites-popup-3d-festa-junina-10un',
    description:
      'Convites pop-up 3D no tema festa junina. Ao abrir, revela uma fogueira em 3D com bandeirinhas. Papel couchê 300g com corte especial a laser. Personalização de texto inclusa.',
    shortDescription: 'Convites pop-up 3D festa junina com fogueira - 10 un.',
    price: 59.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'convites',
    subcategory: 'especiais',
    images: ['https://picsum.photos/seed/conv5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/conv5/300/300',
    badges: ['exclusivo'],
    specifications: {
      Papel: 'Couchê 300g + corte a laser',
      Quantidade: '10 convites',
      Tamanho: '12cm x 12cm (fechado)',
      Efeito: 'Pop-up 3D ao abrir',
    },
    stock: 45,
    sku: 'CONV-POP3D-JUNINA-10',
    weight: 0.15,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 19.97,
  },

  // ── FANTASIAS (4 new) ──────────────────────────────────────────────
  {
    id: '10000008-0001-4000-a008-000000000001',
    name: 'Fantasia Adulto Super-Herói com Capa e Máscara',
    slug: 'fantasia-adulto-super-heroi-capa-mascara',
    description:
      'Fantasia adulto de super-herói com body macacão, capa acetinada e máscara. Tecido stretch confortável. Tamanhos P a GG. Disponível em vermelho/azul e preto/amarelo.',
    shortDescription: 'Fantasia adulto super-herói com capa e máscara.',
    price: 109.9,
    originalPrice: 139.9,
    currency: 'BRL',
    category: 'fantasias',
    subcategory: 'adulto',
    images: ['https://picsum.photos/seed/fant2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/fant2/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'Poliéster stretch + cetim',
      'Tamanhos disponíveis': 'P, M, G, GG',
      'Itens inclusos': 'Macacão, capa, máscara',
      Cores: 'Vermelho/Azul ou Preto/Amarelo',
    },
    stock: 40,
    sku: 'FANT-HERO-AD',
    weight: 0.5,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 36.63,
  },
  {
    id: '10000008-0001-4000-a008-000000000002',
    name: 'Fantasia Infantil Pirata Completa com Acessórios',
    slug: 'fantasia-infantil-pirata-completa-acessorios',
    description:
      'Fantasia infantil de pirata com camisa listrada, colete, bandana, tapa-olho, gancho plástico e espada de espuma. Seguro e divertido. Tamanhos P (3-5 anos), M (6-8 anos) e G (9-11 anos).',
    shortDescription: 'Fantasia pirata infantil completa com 6 acessórios.',
    price: 69.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'fantasias',
    subcategory: 'infantil',
    images: ['https://picsum.photos/seed/fant3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/fant3/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'Poliéster + espuma EVA',
      'Tamanhos disponíveis': 'P, M, G',
      'Faixa etária': '3 a 11 anos',
      'Itens inclusos': 'Camisa, colete, bandana, tapa-olho, gancho, espada',
    },
    stock: 50,
    sku: 'FANT-PIRAT-INF',
    weight: 0.35,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 23.3,
  },
  {
    id: '10000008-0001-4000-a008-000000000003',
    name: 'Fantasia Pet Abelha - Cachorros Pequenos e Médios',
    slug: 'fantasia-pet-abelha-cachorros',
    description:
      'Fantasia para pets em formato de abelha com asinhas e anteninhas. Tecido macio e confortável. Tamanhos PP (até 2kg), P (2-5kg) e M (5-10kg). Perfeita para festas temáticas e ensaios fotográficos com pets.',
    shortDescription: 'Fantasia de abelha para cães pequenos e médios.',
    price: 44.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'fantasias',
    subcategory: 'pet',
    images: ['https://picsum.photos/seed/fant4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/fant4/300/300',
    badges: ['novo', 'exclusivo'],
    specifications: {
      Material: 'Pelúcia + feltro',
      Tamanhos: 'PP (até 2kg), P (2-5kg), M (5-10kg)',
      'Itens inclusos': 'Roupa + asinhas + anteninhas',
      Lavável: 'Sim, à mão',
    },
    stock: 60,
    sku: 'FANT-PET-ABEL',
    weight: 0.15,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 22.45,
  },
  {
    id: '10000008-0001-4000-a008-000000000004',
    name: 'Kit Fantasia Família Circo - 4 Personagens',
    slug: 'kit-fantasia-familia-circo-4-personagens',
    description:
      'Kit família com 4 fantasias tema circo: Mágico (adulto M/G), Palhaço (adulto M/G), Bailarina (infantil P/M/G) e Domador (infantil P/M/G). Ideal para festas temáticas onde toda a família participa.',
    shortDescription: 'Kit 4 fantasias família tema circo (2 adultos + 2 infantis).',
    price: 259.9,
    originalPrice: 349.9,
    currency: 'BRL',
    category: 'fantasias',
    subcategory: 'kits',
    images: ['https://picsum.photos/seed/fant5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/fant5/300/300',
    badges: ['promocao'],
    specifications: {
      Personagens: 'Mágico, Palhaço, Bailarina, Domador',
      'Adulto tamanhos': 'M e G',
      'Infantil tamanhos': 'P, M e G',
      'Total peças': '16 peças (4 fantasias completas)',
    },
    stock: 15,
    sku: 'FANT-FAM-CIRCO-4',
    weight: 1.8,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 43.32,
  },

  // ── ACESSORIOS (4 new) ─────────────────────────────────────────────
  {
    id: '10000009-0001-4000-a009-000000000001',
    name: 'Tiara Orelha de Gato com LED - Kit 5 Cores',
    slug: 'tiara-orelha-gato-led-kit-5-cores',
    description:
      'Kit com 5 tiaras com orelhas de gato e LED piscante em cores variadas (rosa, azul, vermelho, verde e roxo). 3 modos de luz. Bateria inclusa e substituível. Sucesso em festas e eventos.',
    shortDescription: 'Kit 5 tiaras orelha de gato com LED em cores sortidas.',
    price: 39.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'acessorios',
    subcategory: 'luminosos',
    images: ['https://picsum.photos/seed/acess2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/acess2/300/300',
    badges: ['novo'],
    specifications: {
      Quantidade: '5 tiaras',
      'Modos de luz': '3 modos',
      Cores: '5 cores sortidas',
      Bateria: 'CR2032 inclusa',
    },
    stock: 100,
    sku: 'ACESS-TIARA-GATO-5',
    weight: 0.3,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 19.95,
  },
  {
    id: '10000009-0001-4000-a009-000000000002',
    name: 'Chapéu de Festa Cone Holográfico - 12 unidades',
    slug: 'chapeu-festa-cone-holografico-12un',
    description:
      'Kit com 12 chapéus cone de festa com acabamento holográfico multicolorido. Elástico para fixação no queixo. Tamanho padrão que serve crianças e adultos.',
    shortDescription: 'Chapéus cone holográficos para festa - 12 un.',
    price: 22.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'acessorios',
    subcategory: 'chapeus',
    images: ['https://picsum.photos/seed/acess3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/acess3/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'Papel cartão holográfico',
      Quantidade: '12 unidades',
      Fixação: 'Elástico',
      'Tamanho único': 'Crianças e adultos',
    },
    stock: 200,
    sku: 'ACESS-CHAP-HOLO-12',
    weight: 0.15,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000009-0001-4000-a009-000000000003',
    name: 'Língua de Sogra Metalizada - Kit 20 unidades',
    slug: 'lingua-sogra-metalizada-kit-20un',
    description:
      'Kit com 20 línguas de sogra metalizadas em cores sortidas. Material resistente com som de apito. Clássico e indispensável para a hora do parabéns e comemorações.',
    shortDescription: 'Línguas de sogra metalizadas sortidas - 20 un.',
    price: 16.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'acessorios',
    subcategory: 'apitos',
    images: ['https://picsum.photos/seed/acess4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/acess4/300/300',
    badges: [],
    specifications: {
      Material: 'Papel metalizado + plástico',
      Quantidade: '20 unidades',
      Cores: 'Sortidas',
      Som: 'Apito integrado',
    },
    stock: 300,
    sku: 'ACESS-LING-MET-20',
    weight: 0.12,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000009-0001-4000-a009-000000000004',
    name: 'Kit Photo Booth Props Festa - 30 Plaquinhas Divertidas',
    slug: 'kit-photo-booth-props-festa-30-plaquinhas',
    description:
      'Kit com 30 plaquinhas divertidas para photo booth em festas. Inclui bigodes, óculos, lábios, coroas, chapéus e frases engraçadas. Impressas em papel couchê 300g com palitos de madeira.',
    shortDescription: 'Kit 30 plaquinhas photo booth para fotos divertidas.',
    price: 34.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'acessorios',
    subcategory: 'photo-booth',
    images: ['https://picsum.photos/seed/acess5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/acess5/300/300',
    badges: ['exclusivo', 'mais-vendido'],
    specifications: {
      Material: 'Papel couchê 300g + palito de madeira',
      Quantidade: '30 plaquinhas',
      Modelos: 'Bigodes, óculos, coroas, frases e mais',
      'Tamanho médio': '15cm a 25cm',
    },
    stock: 85,
    sku: 'ACESS-PHOTO-30',
    weight: 0.25,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 17.45,
  },

  // ── PERSONALIZADOS (4 new) ─────────────────────────────────────────
  {
    id: '10000010-0001-4000-a010-000000000001',
    name: 'Topo de Bolo Personalizado em Acrílico Espelhado Dourado',
    slug: 'topo-bolo-personalizado-acrilico-espelhado-dourado',
    description:
      'Topo de bolo personalizado em acrílico espelhado dourado com corte a laser. Personalização com nome e idade. Altura 15cm + espeto 10cm. Reutilizável e lavável. Envio em até 5 dias úteis.',
    shortDescription: 'Topo de bolo acrílico espelhado dourado personalizado.',
    price: 39.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'personalizados',
    subcategory: 'topos-de-bolo',
    images: ['https://picsum.photos/seed/pers2/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/pers2/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'Acrílico espelhado 2mm',
      'Altura topo': '15cm',
      'Espeto': '10cm',
      Personalização: 'Nome + idade',
    },
    stock: 50,
    sku: 'PERS-TOPO-ACR-DOU',
    weight: 0.05,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 19.95,
  },
  {
    id: '10000010-0001-4000-a010-000000000002',
    name: 'Caixinha Personalizada Lembrancinha - 20 unidades',
    slug: 'caixinha-personalizada-lembrancinha-20un',
    description:
      'Caixinhas para lembrancinha em papel couchê 300g com impressão personalizada (nome, data e tema). Formato cubo 7x7x7cm. Acompanham laço de fita de cetim na cor escolhida. Entrega em 7 dias úteis.',
    shortDescription: 'Caixinhas lembrancinha personalizadas com laço - 20 un.',
    price: 64.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'personalizados',
    subcategory: 'lembrancinhas',
    images: ['https://picsum.photos/seed/pers3/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/pers3/300/300',
    badges: ['novo'],
    specifications: {
      Material: 'Papel couchê 300g + cetim',
      Quantidade: '20 caixinhas',
      Dimensões: '7cm x 7cm x 7cm',
      Personalização: 'Nome, data e tema',
    },
    stock: 40,
    sku: 'PERS-CX-LEMB-20',
    weight: 0.3,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 21.63,
  },
  {
    id: '10000010-0001-4000-a010-000000000003',
    name: 'Rótulo Personalizado para Garrafa de Água - 30 unidades',
    slug: 'rotulo-personalizado-garrafa-agua-30un',
    description:
      'Rótulos adesivos personalizados para garrafa de água 500ml. Impressão em vinil adesivo à prova d\'água. Personalização com nome, tema e data da festa. Entrega em 5 dias úteis.',
    shortDescription: 'Rótulos personalizados para garrafa de água - 30 un.',
    price: 29.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'personalizados',
    subcategory: 'rotulos',
    images: ['https://picsum.photos/seed/pers4/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/pers4/300/300',
    badges: ['exclusivo'],
    specifications: {
      Material: 'Vinil adesivo à prova d\'água',
      Quantidade: '30 rótulos',
      'Para garrafas': '500ml',
      Personalização: 'Nome, tema e data',
    },
    stock: 70,
    sku: 'PERS-ROT-GAR-30',
    weight: 0.08,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: '10000010-0001-4000-a010-000000000004',
    name: 'Painel de Recados Personalizado em MDF - 60x40cm',
    slug: 'painel-recados-personalizado-mdf-60x40cm',
    description:
      'Painel de recados em MDF branco com moldura e caneta permanente inclusa. Personalização com nome do aniversariante e data. Os convidados deixam mensagens carinhosas. Peça decorativa e lembrança da festa.',
    shortDescription: 'Painel MDF para recados personalizado 60x40cm.',
    price: 79.9,
    originalPrice: 99.9,
    currency: 'BRL',
    category: 'personalizados',
    subcategory: 'paineis',
    images: ['https://picsum.photos/seed/pers5/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/pers5/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'MDF branco 3mm + moldura',
      Dimensões: '60cm x 40cm',
      'Incluso': 'Caneta permanente dourada',
      Personalização: 'Nome e data',
    },
    stock: 20,
    sku: 'PERS-PAIN-MDF-60',
    weight: 1.2,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 26.63,
  },
] as const;

async function main() {
  console.log('Seeding database...');

  const adminPasswordHash = await bcrypt.hash('Admin@123456', 12);
  await prisma.user.upsert({
    where: { email: 'admin@alegrafestas.com.br' },
    update: {},
    create: {
      email: 'admin@alegrafestas.com.br',
      username: 'admin',
      passwordHash: adminPasswordHash,
      name: 'Admin Alegra Festas',
      role: 'ADMIN',
    },
  });
  console.log('  Admin user created: admin@alegrafestas.com.br (admin) / Admin@123456');

  for (const product of PRODUCTS) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: {},
      create: {
        id: product.id,
        name: product.name,
        slug: product.slug,
        description: product.description,
        shortDescription: product.shortDescription,
        price: product.price,
        originalPrice: product.originalPrice,
        currency: product.currency,
        category: product.category,
        subcategory: product.subcategory,
        images: [...product.images],
        thumbnailUrl: product.thumbnailUrl,
        badges: [...product.badges],
        specifications: product.specifications,
        stock: product.stock,
        sku: product.sku,
        weight: product.weight,
        isActive: product.isActive,
        maxInstallments: product.maxInstallments,
        installmentPrice: product.installmentPrice,
      },
    });
  }
  console.log(`  ${PRODUCTS.length} products seeded`);

  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
