import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const PRODUCTS = [
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Kit Balões Metálicos Dourado e Roxo - 50 unidades',
    slug: 'kit-baloes-metalicos-dourado-roxo-50un',
    description:
      'Kit premium com 50 balões metálicos nas cores dourado e roxo. Ideais para decoração de festas de aniversário, casamentos e eventos corporativos. Feitos em látex de alta qualidade com acabamento metalizado.',
    shortDescription: 'Kit com 50 balões metálicos dourado e roxo para festas.',
    price: 49.9,
    originalPrice: 69.9,
    currency: 'BRL',
    category: 'baloes',
    subcategory: 'metalicos',
    images: ['https://picsum.photos/seed/baloes1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/baloes1/300/300',
    badges: ['mais-vendido', 'promocao'],
    specifications: {
      Material: 'Látex metalizado',
      Quantidade: '50 unidades',
      Tamanho: '12 polegadas',
      Cores: 'Dourado e Roxo',
    },
    stock: 150,
    sku: 'BAL-MET-DR-50',
    weight: 0.3,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 16.63,
  },
  {
    id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Conjunto Pratos e Copos Descartáveis Premium - 100 peças',
    slug: 'conjunto-pratos-copos-descartaveis-premium-100pc',
    description:
      'Conjunto completo com 50 pratos e 50 copos descartáveis premium. Material resistente e elegante, perfeito para festas e eventos. Disponível na cor branca com borda dourada.',
    shortDescription: '100 peças de pratos e copos descartáveis premium.',
    price: 89.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'descartaveis',
    subcategory: 'conjuntos',
    images: ['https://picsum.photos/seed/desc1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/desc1/300/300',
    badges: ['novo'],
    specifications: {
      Material: 'Plástico rígido PP',
      Quantidade: '50 pratos + 50 copos',
      'Capacidade copo': '300ml',
      'Tamanho prato': '23cm',
    },
    stock: 80,
    sku: 'DESC-PC-PREM-100',
    weight: 1.2,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 29.97,
  },
  {
    id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'Cortina de Franja Metalizada Rosa Gold',
    slug: 'cortina-franja-metalizada-rosa-gold',
    description:
      'Cortina decorativa de franja metalizada na cor rosa gold. Dimensões 1m x 2m. Perfeita para fundo de mesa de bolo, photobooth e decoração de ambientes.',
    shortDescription: 'Cortina metalizada rosa gold 1m x 2m.',
    price: 24.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'decoracao',
    subcategory: 'cortinas',
    images: ['https://picsum.photos/seed/cortina1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/cortina1/300/300',
    badges: ['mais-vendido'],
    specifications: {
      Material: 'PET metalizado',
      Dimensões: '1m x 2m',
      Cor: 'Rosa Gold',
      Fixação: 'Fita adesiva inclusa',
    },
    stock: 200,
    sku: 'DEC-CORT-RG-1X2',
    weight: 0.15,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: 'd4e5f6a7-b8c9-0123-def0-234567890123',
    name: 'Kit Festa Completo Tema Unicórnio - 16 Convidados',
    slug: 'kit-festa-completo-unicornio-16-convidados',
    description:
      'Kit festa completo tema unicórnio para 16 convidados. Inclui pratos, copos, guardanapos, toalha de mesa, convites, forminhas para doce e chapéus. Tudo coordenado no tema.',
    shortDescription: 'Kit festa unicórnio completo para 16 convidados.',
    price: 129.9,
    originalPrice: 159.9,
    currency: 'BRL',
    category: 'kits',
    subcategory: 'tematicos',
    images: ['https://picsum.photos/seed/kit1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/kit1/300/300',
    badges: ['promocao', 'mais-vendido'],
    specifications: {
      Convidados: '16 pessoas',
      'Itens inclusos': '7 tipos de itens',
      Tema: 'Unicórnio',
      'Total peças': '112 peças',
    },
    stock: 45,
    sku: 'KIT-UNI-16',
    weight: 1.8,
    isActive: true,
    maxInstallments: 6,
    installmentPrice: 21.65,
  },
  {
    id: 'e5f6a7b8-c9d0-1234-ef01-345678901234',
    name: 'Forminha para Doces Luxo Dourada - 100 unidades',
    slug: 'forminha-doces-luxo-dourada-100un',
    description:
      'Forminhas para doces finos em papel laminado dourado. Modelo luxo com recorte em pétala. Ideais para brigadeiros, bem-casados e docinhos finos.',
    shortDescription: 'Forminhas douradas luxo para docinhos - 100 un.',
    price: 34.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'doces',
    subcategory: 'forminhas',
    images: ['https://picsum.photos/seed/forminha1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/forminha1/300/300',
    badges: ['exclusivo'],
    specifications: {
      Material: 'Papel laminado',
      Quantidade: '100 unidades',
      Modelo: 'Pétala luxo',
      'Diâmetro base': '3.5cm',
    },
    stock: 300,
    sku: 'DOC-FORM-LUXO-100',
    weight: 0.1,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: 'f6a7b8c9-d0e1-2345-f012-456789012345',
    name: 'Vela Número Gigante Glitter - Todas as Idades',
    slug: 'vela-numero-gigante-glitter',
    description:
      'Vela decorativa em formato de número com acabamento glitter. Altura de 12cm. Disponível em todos os números de 0 a 9. Longa duração de queima.',
    shortDescription: 'Vela número gigante com glitter, 12cm.',
    price: 18.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'velas',
    subcategory: null,
    images: ['https://picsum.photos/seed/vela1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/vela1/300/300',
    badges: ['novo'],
    specifications: {
      Altura: '12cm',
      Material: 'Parafina com glitter',
      'Tempo queima': '~15 minutos',
      'Números disponíveis': '0 a 9',
    },
    stock: 500,
    sku: 'VEL-NUM-GLIT',
    weight: 0.05,
    isActive: true,
    maxInstallments: 1,
    installmentPrice: null,
  },
  {
    id: 'a7b8c9d0-e1f2-3456-0123-567890123456',
    name: 'Convites Personalizados Festa Tropical - 20 unidades',
    slug: 'convites-personalizados-festa-tropical-20un',
    description:
      'Kit com 20 convites impressos em papel couchê 300g no tema festa tropical. Inclui envelopes kraft. Personalização de nome e data da festa inclusa.',
    shortDescription: 'Convites festa tropical com envelopes - 20 un.',
    price: 42.0,
    originalPrice: null,
    currency: 'BRL',
    category: 'convites',
    subcategory: 'impressos',
    images: ['https://picsum.photos/seed/convite1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/convite1/300/300',
    badges: [],
    specifications: {
      Papel: 'Couchê 300g',
      Quantidade: '20 convites + 20 envelopes',
      Tamanho: '10cm x 15cm',
      Personalização: 'Nome e data',
    },
    stock: 60,
    sku: 'CONV-TROP-20',
    weight: 0.25,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 21.0,
  },
  {
    id: 'b8c9d0e1-f2a3-4567-1234-678901234567',
    name: 'Fantasia Infantil Princesa com Tiara e Varinha',
    slug: 'fantasia-infantil-princesa-tiara-varinha',
    description:
      'Fantasia infantil de princesa com vestido em tule, tiara com pedras brilhantes e varinha mágica. Disponível nos tamanhos P (2-4 anos), M (5-7 anos) e G (8-10 anos).',
    shortDescription: 'Fantasia princesa com tiara e varinha para crianças.',
    price: 79.9,
    originalPrice: 99.9,
    currency: 'BRL',
    category: 'fantasias',
    subcategory: 'infantil',
    images: ['https://picsum.photos/seed/fantasia1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/fantasia1/300/300',
    badges: ['promocao'],
    specifications: {
      Material: 'Poliéster e tule',
      'Tamanhos disponíveis': 'P, M, G',
      'Faixa etária': '2 a 10 anos',
      'Itens inclusos': 'Vestido, tiara, varinha',
    },
    stock: 35,
    sku: 'FANT-PRINC-KIT',
    weight: 0.4,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 26.63,
  },
  {
    id: 'c9d0e1f2-a3b4-5678-2345-789012345678',
    name: 'Óculos Festa Neon LED - Kit 10 Unidades Cores Sortidas',
    slug: 'oculos-festa-neon-led-kit-10un',
    description:
      'Kit com 10 óculos de festa com LED neon em cores sortidas (rosa, verde, azul, amarelo, vermelho). 3 modos de luz: fixo, pisca lento e pisca rápido. Bateria inclusa.',
    shortDescription: 'Kit 10 óculos neon LED cores sortidas para festa.',
    price: 59.9,
    originalPrice: null,
    currency: 'BRL',
    category: 'acessorios',
    subcategory: 'luminosos',
    images: ['https://picsum.photos/seed/oculos1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/oculos1/300/300',
    badges: ['mais-vendido', 'novo'],
    specifications: {
      Quantidade: '10 unidades',
      Cores: '5 cores sortidas',
      'Modos de luz': '3 modos',
      Bateria: 'CR2032 inclusa',
    },
    stock: 120,
    sku: 'ACESS-OCULOS-LED-10',
    weight: 0.5,
    isActive: true,
    maxInstallments: 3,
    installmentPrice: 19.97,
  },
  {
    id: 'd0e1f2a3-b4c5-6789-3456-890123456789',
    name: 'Faixa de Aniversário Personalizada com Nome - Banner TNT',
    slug: 'faixa-aniversario-personalizada-banner-tnt',
    description:
      'Faixa de aniversário em TNT com impressão personalizada. Inclui nome do aniversariante e idade. Dimensões 1.5m x 0.7m. Acompanha fita para fixação.',
    shortDescription: 'Faixa aniversário personalizada em TNT 1.5m x 0.7m.',
    price: 55.0,
    originalPrice: null,
    currency: 'BRL',
    category: 'personalizados',
    subcategory: 'faixas',
    images: ['https://picsum.photos/seed/faixa1/600/600'],
    thumbnailUrl: 'https://picsum.photos/seed/faixa1/300/300',
    badges: ['exclusivo'],
    specifications: {
      Material: 'TNT laminado',
      Dimensões: '1.5m x 0.7m',
      Personalização: 'Nome e idade',
      Fixação: 'Fita inclusa',
    },
    stock: 25,
    sku: 'PERS-FAIXA-TNT',
    weight: 0.2,
    isActive: true,
    maxInstallments: 2,
    installmentPrice: 27.5,
  },
] as const;

async function main() {
  console.log('Seeding database...');

  const adminPasswordHash = await bcrypt.hash('Admin@123456', 12);
  await prisma.user.upsert({
    where: { email: 'admin@alegrafestas.com.br' },
    update: {},
    create: {
      email: 'admin@alegrafestas.com.br',
      username: 'admin',
      passwordHash: adminPasswordHash,
      name: 'Admin Alegra Festas',
      role: 'ADMIN',
    },
  });
  console.log('  Admin user created: admin@alegrafestas.com.br (admin) / Admin@123456');

  for (const product of PRODUCTS) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: {},
      create: {
        id: product.id,
        name: product.name,
        slug: product.slug,
        description: product.description,
        shortDescription: product.shortDescription,
        price: product.price,
        originalPrice: product.originalPrice,
        currency: product.currency,
        category: product.category,
        subcategory: product.subcategory,
        images: [...product.images],
        thumbnailUrl: product.thumbnailUrl,
        badges: [...product.badges],
        specifications: product.specifications,
        stock: product.stock,
        sku: product.sku,
        weight: product.weight,
        isActive: product.isActive,
        maxInstallments: product.maxInstallments,
        installmentPrice: product.installmentPrice,
      },
    });
  }
  console.log(`  ${PRODUCTS.length} products seeded`);

  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
